name: Deploy to Dev

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: dev_environment
  cancel-in-progress: true

jobs:
  verify-app:
    uses: ./.github/workflows/verify.yml
    secrets: inherit

  deployment:
    needs: verify-app
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      environment: dev
