name: Deploy to Staging

on:
  release:
    types: [prereleased]
  workflow_dispatch:

concurrency:
  group: staging_environment
  cancel-in-progress: true

jobs:
  liquibase-validate:
    runs-on: [self-hosted, linux]
    if: '!github.event.pull_request.draft'
    environment: staging
    steps:
      - uses: actions/checkout@v4
      - name: Run Liquibase Validate
        uses: ITSC/Liquibase-Validate-Action@main
        with:
          ops-key: ${{ secrets.OPS_KEY }}
          vault-name: MCESC RSD Config
          db-secret-path: RSD Staging PostgreSQL

  deployment:
    needs: liquibase-validate
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      environment: staging
      target: ${{ github.ref_name }}
